@startuml
actor ユーザー
actor 管理者
left to right direction
rectangle ショッピングサイト{
	ユーザー -->(ログイン)
	ユーザー -->(ログアウト)
	ユーザー -->(買う)
	ユーザー -->(購入キャンセル)
	ユーザー -->(問い合わせ)
	ユーザー -->(決済する)
	ユーザー -->(見る)
	ユーザー -->(レビューする)
	(ログイン)<--管理者
	(見る)<--管理者
	(商品を見せる)<--管理者
	(ユーザー情報の管理)<--管理者
	(問い合わせ)<--管理者

}
@enduml